const countryRows = [
  ["Afghanistan", "AF", "+93"], ["Albania", "AL", "+355"], ["Algeria", "DZ", "+213"],
  ["Argentina", "AR", "+54"], ["Australia", "AU", "+61"], ["Austria", "AT", "+43"],
  ["Bahrain", "BH", "+973"], ["Bangladesh", "BD", "+880"], ["Belgium", "BE", "+32"],
  ["Brazil", "BR", "+55"], ["Cambodia", "KH", "+855"], ["Cameroon", "CM", "+237"],
  ["Canada", "CA", "+1"], ["Chile", "CL", "+56"], ["China", "CN", "+86"],
  ["Colombia", "CO", "+57"], ["Croatia", "HR", "+385"], ["Denmark", "DK", "+45"],
  ["Egypt", "EG", "+20"], ["Ethiopia", "ET", "+251"], ["France", "FR", "+33"],
  ["Germany", "DE", "+49"], ["Ghana", "GH", "+233"], ["Greece", "GR", "+30"],
  ["Hong Kong", "HK", "+852"], ["India", "IN", "+91"], ["Indonesia", "ID", "+62"],
  ["Iraq", "IQ", "+964"], ["Ireland", "IE", "+353"], ["Italy", "IT", "+39"],
  ["Japan", "JP", "+81"], ["Jordan", "JO", "+962"], ["Kenya", "KE", "+254"],
  ["Kuwait", "KW", "+965"], ["Lebanon", "LB", "+961"], ["Malaysia", "MY", "+60"],
  ["Mexico", "MX", "+52"], ["Morocco", "MA", "+212"], ["Myanmar", "MM", "+95"],
  ["Nepal", "NP", "+977"], ["Netherlands", "NL", "+31"], ["Nigeria", "NG", "+234"],
  ["Oman", "OM", "+968"], ["Pakistan", "PK", "+92"], ["Philippines", "PH", "+63"],
  ["Portugal", "PT", "+351"], ["Qatar", "QA", "+974"], ["Russia", "RU", "+7"],
  ["Saudi Arabia", "SA", "+966"], ["Singapore", "SG", "+65"], ["South Africa", "ZA", "+27"],
  ["South Korea", "KR", "+82"], ["Spain", "ES", "+34"], ["Sri Lanka", "LK", "+94"],
  ["Switzerland", "CH", "+41"], ["Taiwan", "TW", "+886"], ["Tanzania", "TZ", "+255"],
  ["Thailand", "TH", "+66"], ["Turkey", "TR", "+90"], ["Uganda", "UG", "+256"],
  ["Ukraine", "UA", "+380"], ["United Arab Emirates", "AE", "+971"],
  ["United Kingdom", "GB", "+44"], ["United States", "US", "+1"], ["Vietnam", "VN", "+84"],
  ["Zambia", "ZM", "+260"], ["Zimbabwe", "ZW", "+263"],
  ["Azerbaijan", "AZ", "+994"], ["Barbados", "BB", "+1"], ["Belarus", "BY", "+375"],
  ["Benin", "BJ", "+229"], ["Bosnia and Herzegovina", "BA", "+387"], ["Botswana", "BW", "+267"],
  ["Cape Verde", "CV", "+238"], ["Congo DR", "CD", "+243"], ["Costa Rica", "CR", "+506"],
  ["Curacao", "CW", "+599"], ["Czech Republic", "CZ", "+420"], ["Dominican Republic", "DO", "+1"],
  ["Ecuador", "EC", "+593"], ["El Salvador", "SV", "+503"], ["Guatemala", "GT", "+502"],
  ["Haiti", "HT", "+509"], ["Honduras", "HN", "+504"], ["Iran", "IR", "+98"],
  ["Ivory Coast", "CI", "+225"], ["Jamaica", "JM", "+1"], ["Kazakhstan", "KZ", "+7"],
  ["Kyrgyzstan", "KG", "+996"], ["Malawi", "MW", "+265"], ["Mali", "ML", "+223"],
  ["Mauritius", "MU", "+230"], ["Mozambique", "MZ", "+258"], ["Namibia", "NA", "+264"],
  ["New Zealand", "NZ", "+64"], ["Nicaragua", "NI", "+505"], ["Norway", "NO", "+47"],
  ["Panama", "PA", "+507"], ["Paraguay", "PY", "+595"], ["Peru", "PE", "+51"],
  ["Senegal", "SN", "+221"], ["Swaziland", "SZ", "+268"], ["Sweden", "SE", "+46"],
  ["Togo", "TG", "+228"], ["Trinidad and Tobago", "TT", "+1"], ["Tunisia", "TN", "+216"],
  ["Uruguay", "UY", "+598"], ["Uzbekistan", "UZ", "+998"],
];

export const fallbackCountries = countryRows
  .map(([name, iso_code, country_code]) => ({
    name,
    iso_code,
    country_code,
    label: `${name} (${country_code})`,
  }))
  .sort((a, b) => a.name.localeCompare(b.name));
